name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 18.17.1
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.1"
      - name: Install dependencies
        run: npm install
      - name: Printing angular version
        run: npm run ng version
      - name: Build
        run: npm run build
      - name: Deploy to external repository
        uses: "cpina/github-action-push-to-another-repository@main"
        env:
          API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
        with:
          source-directory: dist/call-app-frontend
          destination-github-username: "MukundDholariya2706"
          destination-repository-name: "call-app-frontend-build"
          user-email: "mukunddtridhyatech@gmail.com"
          target-branch: "main"
      - name: LS
        run: ls -l
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_USER_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_USER_SECRET_ACCESS_KEY_ID}}
          aws-region: us-east-1
